config/routes.rb
TimeAndBillingApp::Application.routes.draw do
  namespace :admin do resources :clients end
  
  devise_for :users
  resources :projects
  resources :clients
  resources :tasks
  resources :invoices
   

  namespace "admin" do
    root :to => "home#index"
    resources :projects
    resources :clients
    resources :tasks
    resources :invoices
    resources :journal_entries
  end
  

  root :to => 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :contact
  validates_uniqueness_of :email

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  validates_numericality_of :amount
  validates_presence_of :client_id
  validates_presence_of :invoice_number
  validates_presence_of :due_at
  validates_presence_of :sent_at
  validates_presence_of :subject
  validates_presence_of :remit_to
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  has_one :task
  validates_numericality_of :hours
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client
  has_and_belongs_to_many :tasks
  validates_numericality_of :budget
  validates_presence_of :name
  validates_presence_of :client_id
  validates_numericality_of :hour_cap
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_and_belongs_to_many :projects
  validates_presence_of :name
  validates_presence_of :rate
  validates_numericality_of :rate
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  
  respond_to :html
  before_filter :get_client, :except => [:index, :create]
  
  def index
    @clients = Client.all
    respond_with(@clients)
  end
  
  def show
    respond_with(@client)
  end
  
  def new
    
  end
  
  def edit
    
  end
  
  def create
    @client = Client.new(params[:client])
    if @client.save
      flash[:notice] = "Created"
    else
      flash[:alert] = "Error"
    end
    redirect_to admin_clients_path
  end
  
  def update
    if @client.update_attributes(params[:client])
      flash[:notice] = "Updated"
    else
      flash[:alert] = "Error"
    end
    redirect_to admin_clients_path
  end
  
  def destroy
    if @client.destroy
      flash[:notice] = "Destroyed"
    else
      flash[:alert] = "Error"
    end
    respond_with([:admin, @client])
  end
  
  private
  
  def get_client
    @client = params[:id].present? ? Client.find(params[:id]) : Client.new
  end
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < ApplicationController
respond_to :html
before_filter :get_invoice, :except => [:index,:create]

def index
  @invoices = Invoice.all
  respond_with(@invoices)
end

def show
  respond_with(@invoice)
end

def new
  @invoice.due_at = Date.today
  @invoice.sent_at = Date.today
end

def edit

end

def create
  @invoice = Invoice.new(params[:invoice])
  if @invoice.save
    redirect_to admin_invoices_path, :notice => "Created ..."
  else
    flash[:alert] = "Error"
    render :action => 'new'
  end
  
end

def update
  if @invoice.update_attributes(params[:invoice])
    redirect_to admin_invoices_path, :notice => "Updated ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

def destroy
  
  if @invoice.destroy
    redirect_to admin_invoices_path, :notice => "Destroyed ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

private
  def get_invoice
    @invoice = params[:id].present? ? Invoice.find(params[:id]) : Invoice.new
  end

end

app/controllers/admin/journal_entries_controller.rb
class Admin::JournalEntriesController < ApplicationController
respond_to :html
before_filter :get_journal_entry, :except => [:index,:create]
before_filter :authenticate_user!

def index
  @journal_entries = JournalEntry.all
  respond_with(@journal_entries)
end

def show
  respond_with(@journal_entry)
end

def new
  @journal_entry.user_id = current_user.id
  @journal_entry.entered_at = Date.today

end

def edit

end

def create
  @journal_entry = JournalEntry.new(params[:journal_entry])
  if @journal_entry.save
    redirect_to admin_journal_entries_path, :notice => "Created ..."
  else
    flash[:alert] = "Error"
    render :action => 'new'
  end
  
end

def update
  if @journal_entry.update_attributes(params[:journal_entry])
    redirect_to admin_journal_entries_path, :notice => "Updated ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

def destroy
  
  if @journal_entry.destroy
    redirect_to admin_journal_entries_path, :notice => "Destroyed ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

private
  def get_journal_entry
    @journal_entry = params[:id].present? ? JournalEntry.find(params[:id]) : JournalEntry.new
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
respond_to :html
before_filter :get_project, :except => [:index,:create]

def index
  @projects = Project.all
  respond_with(@projects)
end

def show
  respond_with(@project)
end

def new

end

def edit

end

def create
  @project = Project.new(params[:project])
  if @project.save
    redirect_to admin_projects_path, :notice => "Created ..."
  else
    flash[:alert] = "Error"
    render :action => 'new'
  end
  
end

def update
  if @project.update_attributes(params[:project])
    redirect_to admin_projects_path, :notice => "Updated ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

def destroy
  
  if @project.destroy
    redirect_to admin_projects_path, :notice => "Destroyed ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

private
  def get_project
    @project = params[:id].present? ? Project.find(params[:id]) : Project.new
  end

end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
respond_to :html
before_filter :get_task, :except => [:index,:create]

def index
  @tasks = Task.all
  respond_with(@tasks)
end

def show
  respond_with(@task)
end

def new

end

def edit

end

def create
  @task = Task.new(params[:task])
  if @task.save
    redirect_to admin_tasks_path, :notice => "Created ..."
  else
    flash[:alert] = "Error"
    render :action => 'new'
  end
  
end

def update
  if @task.update_attributes(params[:task])
    redirect_to admin_tasks_path, :notice => "Updated ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

def destroy
  
  if @task.destroy
    redirect_to admin_tasks_path, :notice => "Destroyed ..."
  else
    flash[:alert] = "Error"
    render :action => 'edit'
  end
end

private
  def get_task
    @task = params[:id].present? ? Task.find(params[:id]) : Task.new
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  respond_to :html
  
  
    def index
      
    end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html
  
  
    def index
      
    end
  
    def show
      
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/clients/edit.html.haml
%h1 
  = link_to('Clients', admin_clients_path) 
  >> #{@client.name}
%p
  =semantic_form_for [:admin,@client] do |f|
    =f.inputs
    =f.buttons
%hr
  = link_to("New", new_admin_client_path)
  %br
  = link_to 'Destroy', [:admin,@client], :confirm => 'Are you sure?', :method => :delete

app/views/admin/clients/index.html.haml
%h1 Clients

%ul
  -@clients.each do |c|
    %li=link_to(c.name, edit_admin_client_path(c))
%hr
=link_to("New",new_admin_client_path)

app/views/admin/clients/new.html.erb
<h1>New Client</h1>
<%= semantic_form_for [:admin,@client] do |f| %>
	<%= f.inputs %>
	<%= f.buttons %>
<% end %>

app/views/admin/clients/new.html.haml
%h1 
  = link_to('Clients', admin_clients_path) 
  >> New
%p
  =semantic_form_for [:admin,@client] do |f|
    =f.inputs
    =f.buttons

app/views/admin/invoices/edit.html.haml
%h1 
  = link_to('Invoices', admin_invoices_path) 
  >> #{@invoice.invoice_number}
%p
  =semantic_form_for [:admin,@invoice] do |f|
    =f.inputs
    =f.buttons
%hr
  = link_to("New", new_admin_invoice_path)
  %br
  = link_to 'Destroy', [:admin,@invoice], :confirm => 'Are you sure?', :method => :delete

app/views/admin/invoices/index.html.haml
%h1 Invoices

%ul
  -@invoices.each do |c|
    %li=link_to(c.invoice_number, edit_admin_invoice_path(c))
%hr
=link_to("new",new_admin_invoice_path)

app/views/admin/invoices/new.html.haml
%h1 
  = link_to('Invoices', admin_invoices_path) 
  >> New
%p
  =semantic_form_for [:admin,@invoice] do |f|
    =f.inputs
    =f.buttons

app/views/admin/journal_entries/edit.html.haml
%h1 
  = link_to('Journal_entries', admin_journal_entries_path) 
  >> #{@journal_entry.id}
%p
  =semantic_form_for [:admin,@journal_entry] do |f|
    =f.inputs do
      =f.input :user_id, :as => :hidden
      =f.input :entered_at
      =f.input :project
      =f.input :description
      =f.input :hours
    =f.buttons
%hr
  = link_to("New", new_admin_journal_entry_path)
  %br
  = link_to 'Destroy', [:admin,@journal_entry], :confirm => 'Are you sure?', :method => :delete

app/views/admin/journal_entries/index.html.haml
%h1 Journal_entries

%ul
  -@journal_entries.each do |c|
    %li=link_to(c.entered_at, edit_admin_journal_entry_path(c))
%hr
=link_to("new",new_admin_journal_entry_path)

app/views/admin/journal_entries/new.html.haml
%h1 
  = link_to('Journal', admin_journal_entries_path) 
  >> New
%p
  =semantic_form_for [:admin,@journal_entry] do |f|
    =f.inputs do
      =f.input :user_id, :as => :hidden
      =f.input :entered_at, :as => :hidden
      =f.input :project
      =f.input :hours
      =f.input :description
    =f.buttons

app/views/admin/projects/edit.html.haml
%h1 
  = link_to('Projects', admin_projects_path) 
  >> #{@project.name}
%p
  =semantic_form_for [:admin,@project] do |f|
    =f.inputs
    =f.buttons
%hr
  = link_to("New", new_admin_project_path)
  %br
  = link_to 'Destroy', [:admin,@project], :confirm => 'Are you sure?', :method => :delete

app/views/admin/projects/index.html.haml
%h1 Projects

%ul
  -@projects.each do |c|
    %li=link_to(c.name, edit_admin_project_path(c))
%hr
=link_to("new",new_admin_project_path)

app/views/admin/projects/new.html.haml
%h1 
  = link_to('Projects', admin_projects_path) 
  >> New
%p
  =semantic_form_for [:admin,@project] do |f|
    =f.inputs
    =f.buttons

app/views/admin/tasks/edit.html.haml
%h1 
  = link_to('Tasks', admin_tasks_path) 
  >> #{@task.name}
%p
  =semantic_form_for [:admin,@task] do |f|
    =f.inputs
    =f.buttons
%hr
  = link_to("New", new_admin_task_path)
  %br
  = link_to 'Destroy', [:admin,@task], :confirm => 'Are you sure?', :method => :delete

app/views/admin/tasks/index.html.haml
%h1 Tasks

%ul
  -@tasks.each do |c|
    %li=link_to(c.name, edit_admin_task_path(c))
%hr
=link_to("new",new_admin_task_path)

app/views/admin/tasks/new.html.haml
%h1 
  = link_to('Tasks', admin_tasks_path) 
  >> New
%p
  =semantic_form_for [:admin,@task] do |f|
    =f.inputs
    =f.buttons

app/views/clients/index.html.haml
<h1>Hare Krishna </h1>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Poi
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    <!--[if lt IE 8]><link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
  %body
    #head
      .container
        .column
          %h1=link_to "Poi", "/"
    #flash
      - unless notice.blank?
        .success
          = notice
      - unless alert.blank?
        .alert
          = alert
    #menu
      %ul
        - if user_signed_in?
          %li=link_to "Clients",admin_clients_path
          %li=link_to "Projects", admin_projects_path
          %li=link_to "Tasks", admin_tasks_path
          %li=link_to "Invoices",admin_invoices_path
          %li=link_to "Logout", destroy_user_session_path, :method => :delete
        - else
          %li=link_to "Login", new_user_session_path
    
    #content
      .container
        .column.span-24
          = yield

    #footer

app/views/projects/index.html.haml
<h1>Hare Krishna </h1>

app/views/projects/show.html.haml
<h1>Hare Krishna </h1>